# Generated by Django 4.2.27 on 2026-04-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('arduino_r4', 'Arduino Uno R4'), ('esp32', 'ESP32')], max_length=20)),
                ('test_id', models.CharField(max_length=50)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('error', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=50, null=True)),
                ('free_ram', models.IntegerField(blank=True, null=True)),
                ('min_free_ram', models.IntegerField(blank=True, null=True)),
                ('computation_time', models.FloatField(blank=True, null=True)),
                ('complexity', models.IntegerField(blank=True, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTSimulationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('arduino_r4', 'Arduino Uno R4'), ('esp32', 'ESP32')], max_length=20)),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('devices', models.IntegerField()),
                ('interval', models.FloatField()),
                ('duration', models.IntegerField()),
                ('total_requests', models.IntegerField(blank=True, null=True)),
                ('avg_latency', models.FloatField(blank=True, null=True)),
                ('min_latency', models.FloatField(blank=True, null=True)),
                ('max_latency', models.FloatField(blank=True, null=True)),
                ('p50_latency', models.FloatField(blank=True, null=True)),
                ('p95_latency', models.FloatField(blank=True, null=True)),
                ('p99_latency', models.FloatField(blank=True, null=True)),
                ('requests_per_sec', models.FloatField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTStressTestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('arduino_r4', 'Arduino Uno R4'), ('esp32', 'ESP32')], max_length=20)),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('client_count', models.IntegerField()),
                ('req_per_client', models.IntegerField()),
                ('total_requests', models.IntegerField()),
                ('avg_latency', models.FloatField(blank=True, null=True)),
                ('min_latency', models.FloatField(blank=True, null=True)),
                ('max_latency', models.FloatField(blank=True, null=True)),
                ('p50_latency', models.FloatField(blank=True, null=True)),
                ('p95_latency', models.FloatField(blank=True, null=True)),
                ('p99_latency', models.FloatField(blank=True, null=True)),
                ('requests_per_sec', models.FloatField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFIDRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('arduino_r4', 'Arduino Uno R4'), ('esp32', 'ESP32')], max_length=20)),
                ('test_id', models.CharField(max_length=50)),
                ('rfid_reaction_time', models.FloatField(blank=True, null=True)),
                ('http_latency', models.FloatField(blank=True, null=True)),
                ('led_response_time', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('up_time', models.FloatField(blank=True, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
                ('tls_handshake_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('denied', 'Denied'), ('error', 'Error')], default='error', max_length=10)),
                ('free_ram', models.IntegerField(blank=True, null=True)),
                ('min_free_ram', models.IntegerField(blank=True, null=True)),
                ('wifi_reconnects', models.IntegerField(blank=True, null=True)),
                ('error', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
