# Generated by Django 4.2.27 on 2026-04-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArduinoData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidrequestlog',
            name='tls_handshake_time',
        ),
    ]
